### ISSUE TITLE
Amélioration : Ajustements sur la fonctionnalité de suppression des contacts

### ISSUE THREAD

**Issue by Mohamed11abdallah** [OUMARNDIAYE49/live-coding-contact-vuejs#1]
## Description
Des ajustements ont été apportés à la fonctionnalité de suppression des contacts pour améliorer la précision et la réactivité du processus de suppression.

## Points Clés des Modifications

1. **Débogage** :
   - Ajout de `console.log` pour afficher l'ID du contact à supprimer. Ceci permet de suivre les ID des contacts lorsqu'une suppression est demandée et facilite le débogage des éventuels problèmes.

2. **Utilisation de `splice`** :
   - Modification de la méthode `removeContact` pour utiliser la méthode `splice`. Ce changement assure que la suppression des contacts est plus réactive et efficace en mettant à jour directement le tableau des contacts sans créer de nouvelles références.

3. **Vérifications Générales** :
   - L'ensemble du code a été vérifié pour s'assurer que la suppression des contacts est correctement liée à l'interface utilisateur. Cela inclut la validation que les contacts sont bien supprimés de la liste affichée et que l'état de l'application est correctement mis à jour.

## Comportement Attendu
- **Débogage** : Les ID des contacts supprimés devraient s'afficher dans la console lors de l'opération de suppression, facilitant le suivi et le débogage.
- **Suppression** : Les contacts doivent être correctement supprimés de la liste en utilisant `splice`, assurant que les modifications sont réactives et visibles immédiatement.
- **Vérifications** : Toutes les opérations de suppression doivent être fonctionnelles et correctement reflétées dans l'interface utilisateur.

## Critères de Réussite
- Les `console.log` affichent correctement les ID des contacts à supprimer lors de l'action de suppression.
- La méthode `removeContact` utilise `splice` de manière efficace pour retirer les contacts du tableau.
- Les contacts supprimés ne sont plus affichés dans la liste après la suppression.
- Le code a été testé pour garantir que toutes les fonctionnalités de suppression fonctionnent comme prévu sans introduire de nouveaux problèmes.

## Instructions de Test
1. **Test de Débogage** :
   - Ouvrez la console du navigateur.
   - Exécutez une suppression de contact et vérifiez que l'ID du contact à supprimer est bien affiché dans la console.

2. **Test de Suppression** :
   - Supprimez un contact via l'interface utilisateur.
   - Vérifiez que le contact est effectivement retiré de la liste sans rafraîchir la page.

3. **Test de Vérifications Générales** :
   - Vérifiez que la liste des contacts est correctement mise à jour après chaque opération de suppression.
   - Assurez-vous qu'aucun problème n'est introduit par les modifications apportées.

**Comment by OUMARNDIAYE49** [comment]
Merci pour ta participation
